apiVersion: apps/v1
kind: Deployment
metadata:
  name: driver-api-deployment
  labels:
    app: driver-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: driver-api
  template:
    metadata:
      labels:
        app: driver-api
    spec:
      containers:
        - name: driver-api-container
          image: ghcr.io/org-name/driver-api:1.0
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: driver-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /driver-api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: driver-api-service
                port:
                  number: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: driver-api-service
spec:
  selector:
    app: driver-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---

